"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { BadgeCheck, Building2, CheckCircle2, CircleDollarSign, ClipboardCheck, Search, ShieldCheck, UsersRound, XCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";
import { RECORDS_STORAGE_KEY } from "@/lib/contractor-actions";
import { JobFinder } from "@/components/job-finder";
import type { JobStatus, WorkRecord } from "@/types/work";

const statuses: Array<JobStatus | "All"> = ["All", "Pending Verification", "Verified", "Rejected", "Needs Revision"];
const formatMoney = (value: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);

export function StatusBadge({ status }: { status: JobStatus }) { const styles: Record<JobStatus, string> = { "Pending Verification": "bg-amber-50 text-amber-700", Verified: "bg-emerald-50 text-emerald-700", Rejected: "bg-rose-50 text-rose-700", "Needs Revision": "bg-blue-50 text-blue-700" }; return <Badge className={styles[status]}>{status}</Badge>; }

export function ContractorDashboard() {
  const [records, setRecords] = useState<WorkRecord[]>([]);
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState<JobStatus | "All">("Pending Verification");
  useEffect(() => { const load = () => { try { setRecords(JSON.parse(window.localStorage.getItem(RECORDS_STORAGE_KEY) || "[]")); } catch { setRecords([]); } }; load(); window.addEventListener("storage", load); window.addEventListener("kai-work-records-updated", load); return () => { window.removeEventListener("storage", load); window.removeEventListener("kai-work-records-updated", load); }; }, []);
  const filtered = useMemo(() => records.filter((record) => { const haystack = `${record.workerName} ${record.workerId} ${record.jobType} ${record.status}`.toLowerCase(); return (status === "All" || record.status === status) && haystack.includes(query.toLowerCase()); }), [records, query, status]);
  const pending = records.filter((record) => record.status === "Pending Verification").length;
  const approved = records.filter((record) => record.status === "Verified");
  const rejected = records.filter((record) => record.status === "Rejected").length;
  const averageWage = approved.length ? approved.reduce((sum, record) => sum + record.wage, 0) / approved.length : 0;
  return <main className="min-h-screen bg-[#f5f8fc]"><header className="border-b border-slate-100 bg-white/80 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 sm:px-8"><Link href="/" className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-blue-500 to-blue-700 font-extrabold text-white">K</span><span className="font-[family-name:'Plus_Jakarta_Sans'] text-lg font-extrabold text-slate-900">kai<span className="text-blue-600">.</span></span><span className="hidden border-l border-slate-200 pl-3 text-sm font-semibold text-slate-500 sm:block">Contractor portal</span></Link><Link href="/#dashboard" className="text-sm font-semibold text-blue-600">Worker workspace</Link></div></header><section className="mx-auto max-w-7xl px-5 py-8 sm:px-8"><div className="rounded-3xl bg-gradient-to-r from-[#0d3477] via-[#1557ae] to-[#0b7f88] p-6 text-white sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm text-blue-100">ABC Builders · verified contractor</p><h1 className="mt-1 font-[family-name:'Plus_Jakarta_Sans'] text-2xl font-extrabold">Verification workspace</h1><p className="mt-2 max-w-xl text-sm leading-6 text-blue-100">Review submitted work records before they become part of a worker’s trusted Kai passport.</p></div><div className="flex items-center gap-3 rounded-2xl border border-white/15 bg-white/10 p-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/10"><BadgeCheck className="h-5 w-5 text-emerald-200"/></span><div><p className="text-xs font-bold text-blue-100">CONTRACTOR PROFILE</p><p className="text-sm font-bold">4.9 average rating · 3 years</p></div></div></div></div>
    <div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={ClipboardCheck} label="Pending" value={pending} tone="amber"/><Metric icon={CheckCircle2} label="Approved" value={approved.length} tone="emerald"/><Metric icon={XCircle} label="Rejected" value={rejected} tone="rose"/><Metric icon={CircleDollarSign} label="Avg. verified wage" value={formatMoney(averageWage)} tone="blue"/></div>
    <JobFinder />
    <Card className="mt-6 p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="eyebrow">Verification requests</p><h2 className="mt-1 font-[family-name:'Plus_Jakarta_Sans'] text-xl font-bold text-slate-950">Review worker submissions</h2></div><div className="relative w-full lg:max-w-sm"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search worker, ID, skill or status" className="h-10 w-full rounded-xl border border-slate-200 bg-slate-50 pl-9 pr-3 text-sm outline-none focus:border-blue-400 focus:bg-white"/></div></div><div className="mt-5 flex gap-2 overflow-x-auto pb-1">{statuses.map((item) => <button key={item} onClick={() => setStatus(item)} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-xs font-bold transition ${status === item ? "bg-slate-900 text-white" : "bg-slate-100 text-slate-600 hover:bg-slate-200"}`}>{item}</button>)}</div><div className="mt-5 divide-y divide-slate-100"><AnimatePresence initial={false}>{filtered.length ? filtered.map((record) => <motion.div key={record.id} layout initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="grid gap-3 py-4 md:grid-cols-[1.2fr_1fr_.85fr_.8fr_auto] md:items-center"><div><p className="font-bold text-slate-800">{record.workerName}</p><p className="mt-1 text-xs text-slate-500">{record.workerId} · {record.jobType}</p></div><p className="text-sm text-slate-600">{record.contractorName}</p><p className="text-sm text-slate-600">{record.location}</p><div><p className="text-sm font-bold text-slate-800">{formatMoney(record.wage)}</p><div className="mt-1"><StatusBadge status={record.status}/></div></div><Link href={`/verification/${record.id}`} className="inline-flex h-9 items-center justify-center rounded-xl bg-blue-600 px-3 text-xs font-bold text-white hover:bg-blue-700">Review</Link></motion.div>) : <div className="py-14 text-center"><UsersRound className="mx-auto h-8 w-8 text-slate-300"/><p className="mt-3 text-sm font-semibold text-slate-700">No matching requests</p><p className="mt-1 text-sm text-slate-500">New worker submissions will appear here.</p></div>}</AnimatePresence></div></Card>
    <div className="mt-6 grid gap-4 md:grid-cols-3"><Notice icon={CheckCircle2} text="Approved jobs are added to the worker’s trusted passport." tone="emerald"/><Notice icon={ShieldCheck} text="Grok runs only after contractor approval." tone="blue"/><Notice icon={Building2} text="Every decision is recorded in verification history." tone="violet"/></div>
  </section></main>;
}
function Metric({ icon: Icon, label, value, tone }: { icon: typeof ClipboardCheck; label: string; value: string | number; tone: "amber" | "emerald" | "rose" | "blue" }) { const colors = { amber: "bg-amber-50 text-amber-600", emerald: "bg-emerald-50 text-emerald-600", rose: "bg-rose-50 text-rose-600", blue: "bg-blue-50 text-blue-600" }; return <Card className="p-5"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${colors[tone]}`}><Icon className="h-4 w-4"/></span><p className="mt-4 text-2xl font-extrabold text-slate-950">{value}</p><p className="mt-1 text-sm text-slate-500">{label}</p></Card>; }
function Notice({ icon: Icon, text, tone }: { icon: typeof CheckCircle2; text: string; tone: "emerald" | "blue" | "violet" }) { const colors = { emerald: "text-emerald-600", blue: "text-blue-600", violet: "text-violet-600" }; return <Card className="flex items-start gap-3 p-4"><Icon className={`mt-0.5 h-5 w-5 ${colors[tone]}`}/><p className="text-sm leading-6 text-slate-600">{text}</p></Card>; }
