"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { BadgeCheck, BarChart3, BriefcaseBusiness, CalendarDays, ChevronRight, CircleDollarSign, FileAudio, FilePlus2, FileText, HandHeart, HeartPulse, IndianRupee, Landmark, MapPin, Menu, Plus, ShieldAlert, ShieldCheck, Sparkles, TrendingUp, Upload, UserRound, UsersRound, WalletCards, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { fallbackVerification } from "@/lib/verification";
import { fallbackPortfolio } from "@/lib/portfolio";
import type { WorkerVerificationInput } from "@/lib/verification";
import type { JobFormValues, PortfolioReport, VerificationReport, WorkRecord } from "@/types/work";

const EMPTY_FORM: JobFormValues = { workerName: "", workerId: "", jobType: "", contractorName: "", wage: "", hoursWorked: "", location: "", date: "", description: "" };
const STORAGE_KEY = "kai-work-records";
const PORTFOLIO_STORAGE_KEY = "kai-portfolio-summary";

const documents = [
  ["Identity", "Aadhaar, voter ID or other identity proof", UserRound, "blue"],
  ["Certificates", "Skill and trade certificates", BadgeCheck, "emerald"],
  ["Training", "Course and training records", FileText, "violet"],
  ["e-Shram", "e-Shram registration document", BriefcaseBusiness, "amber"],
  ["Insurance", "Policy and coverage documents", HeartPulse, "rose"],
  ["Other documents", "Any helpful supporting evidence", FilePlus2, "slate"],
] as const;

const opportunities = [
  ["Suggested welfare", "Check your eligibility for e-Shram and state worker welfare programs.", Landmark, "Explore schemes"],
  ["Microloan readiness", "Keep a steady work record to support a future application.", WalletCards, "View readiness"],
  ["Insurance guidance", "Find cover that fits your work and family needs.", ShieldCheck, "See suggestions"],
  ["Recommended jobs", "Based on the skills you are recording with Kai.", BriefcaseBusiness, "Browse jobs"],
] as const;

const documentTone = {
  blue: "bg-blue-50 text-blue-600",
  emerald: "bg-emerald-50 text-emerald-600",
  violet: "bg-violet-50 text-violet-600",
  amber: "bg-amber-50 text-amber-600",
  rose: "bg-rose-50 text-rose-600",
  slate: "bg-slate-100 text-slate-600",
} as const;

function formatMoney(value: number) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value); }
function readableDate(value: string) { return value ? new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric" }).format(new Date(`${value}T00:00:00`)) : "—"; }

function Stat({ label, value, detail, icon: Icon, tone = "blue" }: { label: string; value: string; detail: string; icon: typeof BriefcaseBusiness; tone?: "blue" | "green" | "violet" | "amber" }) {
  const toneMap = { blue: "bg-blue-50 text-blue-600", green: "bg-emerald-50 text-emerald-600", violet: "bg-violet-50 text-violet-600", amber: "bg-amber-50 text-amber-600" };
  return <Card className="p-5"><div className="flex items-start justify-between"><span className={`flex h-10 w-10 items-center justify-center rounded-2xl ${toneMap[tone]}`}><Icon className="h-5 w-5"/></span><span className="text-[11px] font-bold text-emerald-600">Live</span></div><p className="mt-5 text-2xl font-extrabold tracking-tight text-slate-950">{value}</p><p className="mt-1 text-sm font-medium text-slate-600">{label}</p><p className="mt-2 text-xs text-slate-400">{detail}</p></Card>;
}

export function Dashboard() {
  const [records, setRecords] = useState<WorkRecord[]>([]);
  const [form, setForm] = useState<JobFormValues>(EMPTY_FORM);
  const [menuOpen, setMenuOpen] = useState(false);
  const [notice, setNotice] = useState("");
  const [isVerifying, setIsVerifying] = useState(false);
  const [portfolio, setPortfolio] = useState<PortfolioReport | null>(null);

  useEffect(() => { const saved = window.localStorage.getItem(STORAGE_KEY); if (saved) { try { const parsed = JSON.parse(saved) as WorkRecord[]; setRecords(parsed.map((record) => record.verification ? record : { ...record, verification: fallbackVerification(record) })); } catch { window.localStorage.removeItem(STORAGE_KEY); } } }, []);
  useEffect(() => { const saved = window.localStorage.getItem(PORTFOLIO_STORAGE_KEY); if (saved) { try { setPortfolio(JSON.parse(saved) as PortfolioReport); } catch { window.localStorage.removeItem(PORTFOLIO_STORAGE_KEY); } } }, []);
  useEffect(() => { if (notice) { const timer = window.setTimeout(() => setNotice(""), 3500); return () => window.clearTimeout(timer); } }, [notice]);

  const stats = useMemo(() => {
    const totalEarnings = records.reduce((sum, item) => sum + item.wage, 0);
    const days = new Set(records.map((item) => item.date)).size || 1;
    const skills = records.reduce<Record<string, number>>((acc, item) => ({ ...acc, [item.jobType]: (acc[item.jobType] || 0) + 1 }), {});
    const mainSkill = Object.entries(skills).sort((a, b) => b[1] - a[1])[0]?.[0] || "Not recorded yet";
    const verified = records.filter((item) => item.verificationStatus === "Verified").length;
    return { totalEarnings, average: totalEarnings / days, mainSkill, verified, verificationRate: records.length ? Math.round((verified / records.length) * 100) : 0 };
  }, [records]);

  const worker = records[0];
  const generatePortfolio = async (history: WorkRecord[]) => {
    let nextPortfolio = fallbackPortfolio(history);
    try {
      const response = await fetch("/api/generate-portfolio", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ records: history }) });
      if (response.ok) { const payload = await response.json() as { portfolio?: PortfolioReport }; if (payload.portfolio) nextPortfolio = payload.portfolio; }
    } catch { /* The locally generated portfolio remains available. */ }
    setPortfolio(nextPortfolio);
    window.localStorage.setItem(PORTFOLIO_STORAGE_KEY, JSON.stringify(nextPortfolio));
  };
  const submitRecord = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!form.workerName || !form.workerId || !form.jobType || !form.wage || !form.date) { setNotice("Please complete the required worker and job details."); return; }
    setIsVerifying(true);
    const workerInput: WorkerVerificationInput = { workerName: form.workerName, workerId: form.workerId, jobType: form.jobType, contractorName: form.contractorName || "Independent", wage: Number(form.wage), hoursWorked: Number(form.hoursWorked || 0), location: form.location || "Not specified", state: form.location || "Not specified", date: form.date, description: form.description };
    let verification = fallbackVerification(workerInput);
    let usedFallback = true;
    try {
      const previousWorkHistory = records.slice(0, 25).map(({ workerName, workerId, jobType, contractorName, wage, hoursWorked, location, date, description }) => ({ workerName, workerId, jobType, contractorName, wage, hoursWorked, location, date, description }));
      const response = await fetch("/api/verify-worker", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ worker: workerInput, previousWorkHistory }) });
      if (response.ok) { const payload = await response.json() as { verification?: VerificationReport; fallback?: boolean }; if (payload.verification) { verification = payload.verification; usedFallback = Boolean(payload.fallback); } }
    } catch { usedFallback = true; }
    const record: WorkRecord = { id: crypto.randomUUID(), ...workerInput, verificationStatus: verification.verificationStatus, verification, createdAt: new Date().toISOString() };
    const next = [record, ...records]; setRecords(next); window.localStorage.setItem(STORAGE_KEY, JSON.stringify(next)); await generatePortfolio(next); setForm({ ...EMPTY_FORM, workerName: form.workerName, workerId: form.workerId }); setNotice(usedFallback ? "Work record saved. AI verification is unavailable, so Kai added a safe placeholder report." : "Work record created and AI verification saved to this browser.");
    setIsVerifying(false);
  };

  return <section id="dashboard" className="scroll-mt-4 bg-[#f5f8fc] py-12 sm:py-16"><div className="mx-auto max-w-7xl px-5 sm:px-8">
    <div className="mb-7 flex items-center justify-between"><div><p className="eyebrow">Your workspace</p><h2 className="section-title mt-2">Build your work passport</h2></div><button onClick={() => setMenuOpen(!menuOpen)} className="rounded-xl border border-slate-200 bg-white p-2.5 text-slate-600 lg:hidden" aria-label="Toggle dashboard menu">{menuOpen ? <X className="h-5 w-5"/> : <Menu className="h-5 w-5"/>}</button></div>
    <div className="grid gap-6 lg:grid-cols-[215px_minmax(0,1fr)]"><aside className={`${menuOpen ? "block" : "hidden"} rounded-3xl border border-white bg-white p-3 shadow-sm lg:block lg:h-fit`}><a href="#record-job" className="flex items-center gap-3 rounded-xl bg-blue-600 px-3 py-2.5 text-sm font-bold text-white"><Plus className="h-4 w-4"/>Record a job</a>{[[BarChart3,"Overview"],[UserRound,"My passport"],[BriefcaseBusiness,"Work history"],[FileText,"Documents"],[Sparkles,"Opportunities"]].map(([Icon, label]) => { const I = Icon as typeof BarChart3; return <a key={String(label)} href={`#${String(label).toLowerCase().replace(" ", "-")}`} onClick={() => setMenuOpen(false)} className="mt-1 flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-slate-600 hover:bg-slate-50"><I className="h-4 w-4"/>{String(label)}</a>; })}<div className="mt-5 rounded-2xl bg-emerald-50 p-4"><Sparkles className="h-5 w-5 text-emerald-600"/><p className="mt-3 text-sm font-bold text-slate-800">Your data stays with you</p><p className="mt-1 text-xs leading-5 text-slate-600">Kai stores records in this browser only.</p></div></aside>
      <div className="min-w-0 space-y-6"><motion.div initial={{ opacity: 0, y: 10 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="rounded-3xl bg-gradient-to-r from-[#0d3477] via-[#1557ae] to-[#117f88] p-6 text-white sm:p-8"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-medium text-blue-100">Your personal work record</p><h3 className="mt-1 font-[family-name:'Plus_Jakarta_Sans'] text-2xl font-extrabold tracking-tight">{worker ? `Welcome back, ${worker.workerName.split(" ")[0]}` : "Let’s make your work count."}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-blue-100">Record a completed job to begin building a portable, professional history of your work.</p></div><div className="rounded-2xl border border-white/15 bg-white/10 px-4 py-3"><p className="text-[11px] font-bold uppercase tracking-wider text-blue-100">Latest trust score</p><p className="mt-1 text-2xl font-extrabold">{worker?.verification.trustScore ?? "—"}<span className="ml-1 text-sm font-medium text-blue-100">/100</span></p></div></div></motion.div>

        {notice && <div role="status" className="rounded-2xl border border-emerald-100 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-800">{notice}</div>}
        <div id="overview" className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Stat icon={BriefcaseBusiness} label="Total jobs" value={String(records.length)} detail="All jobs you recorded"/><Stat icon={IndianRupee} tone="green" label="Total earnings" value={formatMoney(stats.totalEarnings)} detail="Across recorded jobs"/><Stat icon={CalendarDays} tone="violet" label="Average daily wage" value={formatMoney(stats.average)} detail="Based on active work days"/><Stat icon={Sparkles} tone="amber" label="Most common skill" value={stats.mainSkill} detail="From work records"/><Stat icon={ShieldCheck} tone="green" label="Verification rate" value={`${stats.verificationRate}%`} detail={`${stats.verified} verified record${stats.verified === 1 ? "" : "s"}`}/></div>

        <div id="record-job" className="grid gap-6 xl:grid-cols-[1.45fr_.75fr]"><Card className="p-5 sm:p-7"><div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><FilePlus2 className="h-5 w-5"/></span><div><h3 className="font-[family-name:'Plus_Jakarta_Sans'] text-lg font-bold text-slate-950">Record completed work</h3><p className="mt-1 text-sm text-slate-500">A few details today can become useful proof tomorrow.</p></div></div><form onSubmit={submitRecord} className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Worker name" required value={form.workerName} onChange={(value) => setForm({ ...form, workerName: value })} placeholder="Your full name"/><Field label="Worker ID" required value={form.workerId} onChange={(value) => setForm({ ...form, workerId: value })} placeholder="e.g. KAI-10294"/><Field label="Job type / skill" required value={form.jobType} onChange={(value) => setForm({ ...form, jobType: value })} placeholder="e.g. Masonry work"/><Field label="Contractor name" value={form.contractorName} onChange={(value) => setForm({ ...form, contractorName: value })} placeholder="Company or contractor"/><Field label="Wage (₹)" required type="number" value={form.wage} onChange={(value) => setForm({ ...form, wage: value })} placeholder="0"/><Field label="Hours worked" type="number" value={form.hoursWorked} onChange={(value) => setForm({ ...form, hoursWorked: value })} placeholder="8"/><Field label="Location" value={form.location} onChange={(value) => setForm({ ...form, location: value })} placeholder="Area, city"/><Field label="Date" required type="date" value={form.date} onChange={(value) => setForm({ ...form, date: value })}/><label className="sm:col-span-2"><span className="mb-1.5 block text-sm font-semibold text-slate-700">Job description</span><textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Briefly describe the work completed..." rows={3} className="w-full resize-none rounded-xl border border-slate-200 bg-slate-50/70 px-3.5 py-2.5 text-sm outline-none placeholder:text-slate-400 focus:border-blue-400 focus:bg-white focus:ring-2 focus:ring-blue-100"/></label><div className="sm:col-span-2 grid gap-3 sm:grid-cols-2"><UploadTile icon={Upload} title="Supporting document" text="Upload a photo or proof (UI only)"/><UploadTile icon={FileAudio} title="Voice note" text="Add a job voice note (UI only)"/></div><div className="sm:col-span-2 flex flex-col gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs leading-5 text-slate-500">Your work record is saved in your browser. No account needed.</p><Button type="submit"><Sparkles className="h-4 w-4"/>Generate work record</Button></div></form></Card>
          <Card className="overflow-hidden"><div className="border-b border-slate-100 p-6"><p className="eyebrow">Earnings overview</p><h3 className="mt-2 font-[family-name:'Plus_Jakarta_Sans'] text-lg font-bold text-slate-950">Monthly earnings</h3><p className="mt-1 text-sm text-slate-500">A visual summary will grow with your records.</p></div><div className="p-6"><div className="flex h-40 items-end gap-2"><Bar height="33%"/><Bar height="52%"/><Bar height="44%"/><Bar height="70%"/><Bar height="58%"/><Bar height={records.length ? "86%" : "30%"} active/></div><div className="mt-3 flex justify-between text-[10px] font-semibold text-slate-400"><span>Feb</span><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span></div><div className="mt-6 rounded-2xl bg-blue-50 p-4"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-white text-blue-600 shadow-sm"><TrendingUp className="h-4 w-4"/></span><div><p className="text-sm font-bold text-slate-800">Keep recording</p><p className="text-xs text-slate-500">A stronger work history creates a clearer picture.</p></div></div></div></div></Card></div>

        <div id="my-passport" className="grid gap-6 xl:grid-cols-[1.05fr_.95fr]"><Passport records={records} worker={worker} verified={stats.verified}/><div className="space-y-6"><Verification records={records} verificationRate={stats.verificationRate} verification={worker?.verification}/><PortfolioInsights portfolio={portfolio}/></div></div>
        <WorkHistory records={records}/>
        <Documents />
        <Opportunities />
      </div>
    </div>
  </div></section>;
}

function Field({ label, required, value, onChange, placeholder, type = "text" }: { label: string; required?: boolean; value: string; onChange: (value: string) => void; placeholder?: string; type?: string }) { return <label><span className="mb-1.5 block text-sm font-semibold text-slate-700">{label}{required && <span className="text-blue-600"> *</span>}</span><input required={required} type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="h-11 w-full rounded-xl border border-slate-200 bg-slate-50/70 px-3.5 text-sm outline-none placeholder:text-slate-400 focus:border-blue-400 focus:bg-white focus:ring-2 focus:ring-blue-100"/></label>; }
function UploadTile({ icon: Icon, title, text }: { icon: typeof Upload; title: string; text: string }) { return <button type="button" className="flex items-center gap-3 rounded-xl border border-dashed border-slate-200 bg-slate-50/70 p-3 text-left transition hover:border-blue-300 hover:bg-blue-50"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-white text-blue-600 shadow-sm"><Icon className="h-4 w-4"/></span><span><span className="block text-sm font-semibold text-slate-700">{title}</span><span className="block text-xs text-slate-500">{text}</span></span></button>; }
function Bar({ height, active = false }: { height: string; active?: boolean }) { return <div style={{ height }} className={`w-full rounded-t-lg ${active ? "bg-gradient-to-t from-blue-600 to-blue-400" : "bg-blue-100"}`}/>; }

function Passport({ records, worker, verified }: { records: WorkRecord[]; worker?: WorkRecord; verified: number }) { const skills = [...new Set(records.map((item) => item.jobType))].slice(0, 4); return <Card className="overflow-hidden" id="passport"><div className="bg-gradient-to-br from-[#102f6b] to-[#157a85] p-6 text-white sm:p-7"><div className="flex items-start justify-between"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-white/15 text-lg font-extrabold">{worker?.workerName.split(" ").map((piece) => piece[0]).join("").slice(0, 2) || "K"}</div><Badge className="bg-emerald-300/20 text-emerald-100"><BadgeCheck className="mr-1 h-3.5 w-3.5"/>Work passport</Badge></div><h3 className="mt-6 font-[family-name:'Plus_Jakarta_Sans'] text-2xl font-extrabold">{worker?.workerName || "Your name"}</h3><p className="mt-1 text-sm text-blue-100">{worker ? `Worker ID · ${worker.workerId}` : "Add your first work record to begin"}</p><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><div className="rounded-xl bg-white/10 p-3"><p className="text-[10px] font-semibold uppercase tracking-wider text-blue-100">Primary skill</p><p className="mt-1 truncate font-bold">{worker?.jobType || "—"}</p></div><div className="rounded-xl bg-white/10 p-3"><p className="text-[10px] font-semibold uppercase tracking-wider text-blue-100">Experience</p><p className="mt-1 font-bold">{records.length ? "1+ years" : "—"}</p></div></div><div className="mt-3 grid grid-cols-3 gap-2 text-center"><PassportMetric value={String(records.length)} label="Jobs"/><PassportMetric value={String(verified)} label="Verified"/><PassportMetric value={records.length ? "1+" : "—"} label="Years"/></div></div><div className="p-6"><div className="flex items-center justify-between"><h4 className="font-bold text-slate-900">Skills & strengths</h4><span className="text-xs font-semibold text-slate-400">Living profile</span></div><div className="mt-3 flex flex-wrap gap-2">{skills.length ? skills.map((skill) => <Badge key={skill} className="bg-blue-50 text-blue-700">{skill}</Badge>) : <p className="text-sm text-slate-500">Skills will appear here as you record jobs.</p>}</div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-semibold text-slate-400">Languages</p><p className="mt-1 font-bold text-slate-700">Add to profile</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-semibold text-slate-400">Contractor endorsements</p><p className="mt-1 font-bold text-slate-700">Coming soon</p></div></div><Button variant="outline" className="mt-5 w-full"><Upload className="h-4 w-4"/>Download portfolio <span className="text-[10px] font-medium text-slate-400">UI only</span></Button></div></Card>; }
function PassportMetric({ value, label }: { value: string; label: string }) { return <div className="rounded-xl bg-white/10 px-2 py-3"><p className="text-lg font-extrabold">{value}</p><p className="text-[10px] text-blue-100">{label}</p></div>; }

function Verification({ records, verificationRate, verification }: { records: WorkRecord[]; verificationRate: number; verification?: VerificationReport }) { return <Card className="p-6 sm:p-7"><div className="flex items-start justify-between"><div><p className="eyebrow">AI verification report</p><h3 className="mt-2 font-[family-name:'Plus_Jakarta_Sans'] text-lg font-bold text-slate-950">Your trust snapshot</h3></div><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-600"><ShieldCheck className="h-5 w-5"/></span></div><div className="mt-6 flex items-center gap-5 rounded-2xl bg-emerald-50/70 p-4"><div className="flex h-16 w-16 items-center justify-center rounded-full border-[6px] border-emerald-200 bg-white text-lg font-extrabold text-emerald-700">{verification?.trustScore ?? "—"}</div><div><p className="text-sm font-bold text-slate-800">Trust score</p><p className="mt-1 text-xs leading-5 text-slate-600">{verification ? verification.recommendation : "Record work to generate a verification report."}</p></div></div><div className="mt-5 space-y-3"><ReportRow label="Verification status" value={verification?.verificationStatus || (records.length ? `${verificationRate}% recorded` : "Awaiting records")} good={verification?.verificationStatus === "Verified"}/><ReportRow label="Consistency score" value={verification ? `${verification.consistencyScore}/100` : "No history yet"}/><ReportRow label="Fraud risk" value={verification?.fraudRisk || "Awaiting AI review"}/></div><div className="mt-5 rounded-xl border border-blue-100 bg-blue-50/60 p-3"><p className="text-xs font-bold text-blue-800">AI summary {verification?.source === "fallback" && "· Fallback"}</p><p className="mt-1 text-xs leading-5 text-slate-600">{verification?.summary || "Kai will summarize work patterns after your first record is created."}</p>{verification?.workerStrengths.length ? <div className="mt-3 flex flex-wrap gap-1.5">{verification.workerStrengths.map((strength) => <Badge key={strength} className="bg-white text-blue-700">{strength}</Badge>)}</div> : null}</div>{verification?.careerSuggestions.length ? <div className="mt-4"><p className="text-xs font-bold text-slate-700">Career suggestions</p><p className="mt-1 text-xs leading-5 text-slate-500">{verification.careerSuggestions.join(" · ")}</p></div> : null}</Card>; }
function ReportRow({ label, value, good }: { label: string; value: string; good?: boolean }) { return <div className="flex items-center justify-between text-sm"><span className="text-slate-600">{label}</span><span className={`font-bold ${good ? "text-emerald-600" : "text-slate-700"}`}>{value}</span></div>; }

function PortfolioInsights({ portfolio }: { portfolio: PortfolioReport | null }) { return <Card className="p-6 sm:p-7"><div className="flex items-start justify-between"><div><p className="eyebrow">Professional portfolio</p><h3 className="mt-2 font-[family-name:'Plus_Jakarta_Sans'] text-lg font-bold text-slate-950">Career profile</h3></div><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><Sparkles className="h-5 w-5"/></span></div>{portfolio ? <div className="mt-5 space-y-5"><div><p className="text-xs font-bold text-slate-500">PROFESSIONAL SUMMARY {portfolio.source === "fallback" && "· FALLBACK"}</p><p className="mt-1.5 text-sm leading-6 text-slate-700">{portfolio.professionalSummary}</p></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold text-slate-500">EXPERIENCE LEVEL</p><p className="mt-1 text-sm font-bold text-slate-800">{portfolio.experienceLevel}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs font-bold text-slate-500">RELIABILITY</p><p className="mt-1 text-xs leading-5 text-slate-700">{portfolio.reliabilitySummary}</p></div></div><div><p className="text-xs font-bold text-slate-500">TOP SKILLS</p><div className="mt-2 flex flex-wrap gap-1.5">{portfolio.topSkills.map((skill) => <Badge key={skill} className="bg-blue-50 text-blue-700">{skill}</Badge>)}</div></div><PortfolioList title="Career growth suggestions" items={portfolio.careerGrowthSuggestions}/><PortfolioList title="Potential welfare schemes" items={portfolio.potentialWelfareSchemes}/><PortfolioList title="Potential insurance plans" items={portfolio.potentialInsurancePlans}/><div className="rounded-xl border border-amber-100 bg-amber-50/60 p-3"><p className="text-xs font-bold text-amber-800">LOAN READINESS</p><p className="mt-1 text-xs leading-5 text-slate-700">{portfolio.potentialLoanReadinessSummary}</p></div></div> : <div className="mt-5 rounded-xl bg-slate-50 p-4"><p className="text-sm font-semibold text-slate-700">Your portfolio will appear here</p><p className="mt-1 text-xs leading-5 text-slate-500">Save a work record and Grok will generate a professional history summary from all recorded jobs.</p></div>}</Card>; }
function PortfolioList({ title, items }: { title: string; items: string[] }) { return <div><p className="text-xs font-bold text-slate-500">{title.toUpperCase()}</p><ul className="mt-1.5 space-y-1">{items.map((item) => <li key={item} className="flex gap-2 text-xs leading-5 text-slate-700"><ChevronRight className="mt-0.5 h-3.5 w-3.5 shrink-0 text-blue-500"/>{item}</li>)}</ul></div>; }

function WorkHistory({ records }: { records: WorkRecord[] }) { return <Card className="p-5 sm:p-7" id="work-history"><div className="flex items-end justify-between"><div><p className="eyebrow">Work history</p><h3 className="mt-2 font-[family-name:'Plus_Jakarta_Sans'] text-lg font-bold text-slate-950">Completed jobs</h3></div><span className="text-sm font-semibold text-slate-400">{records.length} total</span></div><div className="mt-5 divide-y divide-slate-100">{records.length ? records.map((record) => <div key={record.id} className="grid gap-3 py-4 sm:grid-cols-[1.25fr_1fr_.85fr_.85fr_auto] sm:items-center"><div><p className="font-bold text-slate-800">{record.jobType}</p><p className="mt-1 text-xs text-slate-500">{record.description || "Work record created in Kai"}</p></div><p className="text-sm text-slate-600">{record.contractorName}</p><p className="flex items-center gap-1.5 text-sm text-slate-500"><CalendarDays className="h-3.5 w-3.5"/>{readableDate(record.date)}</p><p className="flex items-center gap-1.5 text-sm text-slate-500"><MapPin className="h-3.5 w-3.5"/>{record.location}</p><div className="sm:text-right"><p className="font-bold text-slate-800">{formatMoney(record.wage)}</p><Badge className={`mt-1 ${record.verificationStatus === "Verified" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{record.verificationStatus}</Badge></div></div>) : <div className="flex flex-col items-center justify-center py-12 text-center"><BriefcaseBusiness className="h-8 w-8 text-slate-300"/><p className="mt-3 text-sm font-semibold text-slate-700">No work records yet</p><p className="mt-1 max-w-sm text-sm text-slate-500">Your completed jobs will form a clear timeline here.</p></div>}</div></Card>; }

function Documents() { return <div id="documents"><div className="mb-4"><p className="eyebrow">Supporting documents</p><h3 className="mt-2 font-[family-name:'Plus_Jakarta_Sans'] text-lg font-bold text-slate-950">Keep helpful proof close by</h3></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{documents.map(([title, description, Icon, tone]) => <Card key={title} className="p-5"><div className="flex items-start justify-between"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${documentTone[tone]}`}><Icon className="h-5 w-5"/></span><Button variant="ghost" size="sm"><Upload className="h-3.5 w-3.5"/>Upload</Button></div><p className="mt-4 font-bold text-slate-800">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></Card>)}</div></div>; }
function Opportunities() { return <div id="opportunities"><div className="mb-4"><p className="eyebrow">Future opportunities</p><h3 className="mt-2 font-[family-name:'Plus_Jakarta_Sans'] text-lg font-bold text-slate-950">More possibilities, as your history grows</h3></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{opportunities.map(([title, description, Icon, action]) => <motion.div whileHover={{ y: -3 }} key={title}><Card className="h-full p-5"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-blue-50 text-blue-600"><Icon className="h-5 w-5"/></span><p className="mt-4 font-bold text-slate-800">{title}</p><p className="mt-2 min-h-12 text-xs leading-5 text-slate-500">{description}</p><button className="mt-5 flex items-center gap-1 text-xs font-bold text-blue-600">{action}<ChevronRight className="h-3.5 w-3.5"/></button></Card></motion.div>)}</div></div>; }
