"use client";

import { motion } from "framer-motion";
import { ArrowRight, BadgeCheck, Banknote, BriefcaseBusiness, Building2, CheckCircle2, FileCheck2, HeartPulse, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const features = [
  { icon: FileCheck2, title: "Your work, on record", body: "Turn every job into a clear, portable proof of your skills and experience.", color: "bg-blue-50 text-blue-600" },
  { icon: ShieldCheck, title: "Built for trust", body: "A structured passport makes it easier for others to understand your work history.", color: "bg-emerald-50 text-emerald-600" },
  { icon: Banknote, title: "Unlock opportunities", body: "Use your records when applying for work, support programs, insurance and more.", color: "bg-violet-50 text-violet-600" },
];

const steps = [
  ["01", "Record a job", "Capture the work you completed in a few simple details."],
  ["02", "Build your passport", "Kai turns your records into a professional work profile."],
  ["03", "Share with confidence", "Present a clearer, stronger picture of your work wherever it matters."],
];

export function Landing() {
  return <div className="overflow-hidden bg-[#f7faff]">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8">
      <a href="#top" className="flex items-center gap-2.5" aria-label="Kai home"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-blue-500 to-blue-700 text-lg font-extrabold text-white shadow-lg shadow-blue-200">K</span><span className="font-[family-name:'Plus_Jakarta_Sans'] text-xl font-extrabold tracking-tight text-slate-900">kai<span className="text-blue-600">.</span></span></a>
      <nav className="hidden items-center gap-7 text-sm font-medium text-slate-600 md:flex"><a href="#how-it-works" className="hover:text-blue-600">How it works</a><a href="#why-kai" className="hover:text-blue-600">Why Kai</a><a href="#passport" className="hover:text-blue-600">Work passport</a></nav>
      <a href="#dashboard" className={buttonVariants({ variant: "secondary", size: "sm" })}>Open workspace <ArrowRight className="h-3.5 w-3.5" /></a>
    </header>

    <main id="top">
      <section className="relative mx-auto max-w-7xl px-5 pb-20 pt-14 sm:px-8 sm:pb-28 sm:pt-20"><div className="grid-pattern absolute inset-x-0 top-0 -z-0 mx-auto h-[480px] max-w-5xl opacity-70 [mask-image:linear-gradient(to_bottom,black,transparent)]"/><div className="absolute -left-28 top-12 -z-10 h-72 w-72 rounded-full bg-blue-200/35 blur-3xl"/><div className="absolute right-0 top-24 -z-10 h-80 w-80 rounded-full bg-emerald-200/35 blur-3xl"/>
        <div className="relative grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><motion.div initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .55 }}><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-blue-100 bg-white/80 px-3 py-1.5 text-xs font-bold text-blue-700 shadow-sm"><Sparkles className="h-3.5 w-3.5"/>AI work passport for every worker</div><h1 className="max-w-3xl font-[family-name:'Plus_Jakarta_Sans'] text-4xl font-extrabold leading-[1.12] tracking-tight text-slate-950 sm:text-5xl lg:text-6xl">Work hard. <span className="text-blue-600">Show the world</span> what it means.</h1><p className="mt-6 max-w-xl text-base leading-7 text-slate-600 sm:text-lg">Kai turns informal work into a professional digital portfolio — a practical record you can carry into your next opportunity.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#dashboard" className={buttonVariants({ size: "lg" })}>Create your work record <ArrowRight className="h-4 w-4"/></a><a href="#how-it-works" className={buttonVariants({ variant: "outline", size: "lg" })}>See how it works</a></div><div className="mt-8 flex flex-wrap gap-x-5 gap-y-2 text-sm font-medium text-slate-600"><span className="flex items-center gap-1.5"><CheckCircle2 className="h-4 w-4 text-emerald-500"/>No paperwork maze</span><span className="flex items-center gap-1.5"><CheckCircle2 className="h-4 w-4 text-emerald-500"/>Private to your browser</span></div></motion.div>
          <motion.div initial={{ opacity: 0, scale: .96 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: .65, delay: .1 }} className="relative mx-auto w-full max-w-md"><div className="absolute -inset-5 rounded-[2.3rem] bg-gradient-to-br from-blue-200/50 to-emerald-100/50 blur-xl"/><div className="relative rounded-[2rem] border border-white bg-white/80 p-5 shadow-[0_25px_80px_rgba(37,99,235,.16)] backdrop-blur"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="h-2.5 w-2.5 rounded-full bg-rose-400"/><span className="h-2.5 w-2.5 rounded-full bg-amber-400"/><span className="h-2.5 w-2.5 rounded-full bg-emerald-400"/></div><span className="text-xs font-semibold text-slate-400">Your work passport</span></div><div className="mt-7 rounded-2xl bg-gradient-to-br from-[#0f2d6d] to-[#1765c3] p-5 text-white"><div className="flex items-start justify-between"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/15 text-lg font-bold">AM</div><BadgeCheck className="h-6 w-6 text-emerald-300"/></div><p className="mt-5 text-xl font-bold">Asha Mehta</p><p className="mt-1 text-sm text-blue-100">Construction & finishing specialist</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/10 p-3"><p className="text-lg font-bold">86</p><p className="text-[11px] text-blue-100">Jobs recorded</p></div><div className="rounded-xl bg-white/10 p-3"><p className="text-lg font-bold">92%</p><p className="text-[11px] text-blue-100">Verified work</p></div></div></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl border border-slate-100 p-3"><p className="text-xs font-semibold text-slate-400">Trust score</p><p className="mt-1 text-xl font-extrabold text-slate-900">847 <span className="text-xs font-medium text-emerald-600">Strong</span></p></div><div className="rounded-xl border border-slate-100 p-3"><p className="text-xs font-semibold text-slate-400">Earnings tracked</p><p className="mt-1 text-xl font-extrabold text-slate-900">₹1.8L</p></div></div></div></motion.div>
        </div>
      </section>

      <section id="why-kai" className="border-y border-slate-100 bg-white/70 py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="max-w-2xl"><p className="eyebrow">A work history that works for you</p><h2 className="section-title mt-3">Your experience has value. Kai makes it visible.</h2><p className="mt-4 leading-7 text-slate-600">Informal workers keep cities and communities moving. Kai helps turn that effort into a clear record that opens more doors.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{features.map(({ icon: Icon, title, body, color }) => <motion.div whileHover={{ y: -4 }} key={title} className="rounded-3xl border border-slate-100 bg-white p-6 shadow-[0_12px_35px_rgba(15,23,42,.04)]"><span className={cn("flex h-11 w-11 items-center justify-center rounded-2xl", color)}><Icon className="h-5 w-5"/></span><h3 className="mt-5 font-[family-name:'Plus_Jakarta_Sans'] text-lg font-bold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{body}</p></motion.div>)}</div></div></section>

      <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-20 sm:px-8"><div className="grid gap-10 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">Simple by design</p><h2 className="section-title mt-3">From job done to proof you can use.</h2><p className="mt-4 max-w-sm leading-7 text-slate-600">No new systems to learn. Simply capture a job as you finish it and let your work history grow over time.</p></div><div className="space-y-4">{steps.map(([number, title, body]) => <div key={number} className="flex gap-5 rounded-2xl border border-slate-100 bg-white p-5 transition hover:border-blue-100 hover:shadow-md"><span className="font-[family-name:'Plus_Jakarta_Sans'] text-sm font-extrabold text-blue-600">{number}</span><div><h3 className="font-bold text-slate-900">{title}</h3><p className="mt-1 text-sm leading-6 text-slate-600">{body}</p></div></div>)}</div></div></section>

      <section id="passport" className="mx-auto max-w-7xl px-5 pb-20 sm:px-8"><div className="overflow-hidden rounded-[2rem] bg-gradient-to-br from-slate-950 via-[#0b387d] to-[#047f81] px-6 py-12 text-white sm:px-12"><div className="grid items-center gap-10 md:grid-cols-[1fr_.7fr]"><div><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white/10"><UsersRound className="h-5 w-5 text-emerald-200"/></div><h2 className="mt-6 font-[family-name:'Plus_Jakarta_Sans'] text-3xl font-extrabold tracking-tight sm:text-4xl">A passport made for the real world of work.</h2><p className="mt-4 max-w-xl leading-7 text-blue-100">Bring your jobs, skills and supporting documents together in one professional place — ready when opportunity calls.</p><a href="#dashboard" className="mt-7 inline-flex h-11 items-center gap-2 rounded-xl bg-white px-4 text-sm font-bold text-blue-800 transition hover:bg-blue-50">Build your passport <ArrowRight className="h-4 w-4"/></a></div><div className="grid grid-cols-2 gap-3"><div className="rounded-2xl border border-white/10 bg-white/10 p-4"><Building2 className="h-5 w-5 text-emerald-200"/><p className="mt-6 text-sm font-bold">Employers</p><p className="mt-1 text-xs leading-5 text-blue-100">A clear view of proven experience.</p></div><div className="rounded-2xl border border-white/10 bg-white/10 p-4"><HeartPulse className="h-5 w-5 text-emerald-200"/><p className="mt-6 text-sm font-bold">Support services</p><p className="mt-1 text-xs leading-5 text-blue-100">Better evidence for better access.</p></div></div></div></div></section>
    </main>
    <footer className="border-t border-slate-100 bg-white py-7"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 px-5 text-sm text-slate-500 sm:flex-row sm:px-8"><p>© 2026 Kai. Work deserves to be seen.</p><p>AI Work Passport for Informal Workers</p></div></footer>
  </div>;
}
