"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { AlertTriangle, ArrowLeft, BadgeCheck, CalendarDays, CheckCircle2, Clock3, FileText, MapPin, MessageSquareWarning, ShieldCheck, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { approveWorkRecord, persistRecords, RECORDS_STORAGE_KEY, refreshVerifiedPortfolio, updateWorkRecordStatus } from "@/lib/contractor-actions";
import type { WorkRecord } from "@/types/work";
import { StatusBadge } from "@/components/contractor-dashboard";

export function VerificationDetails({ recordId }: { recordId: string }) {
  const [records, setRecords] = useState<WorkRecord[]>([]);
  const [reason, setReason] = useState("");
  const [working, setWorking] = useState(false);
  useEffect(() => { try { setRecords(JSON.parse(window.localStorage.getItem(RECORDS_STORAGE_KEY) || "[]")); } catch { setRecords([]); } }, []);
  const record = records.find((item) => item.id === recordId);
  const update = async (decision: "approve" | "reject" | "changes") => {
    if (!record || working) return;
    if (decision !== "approve" && !reason.trim()) return;
    setWorking(true);
    const updated = decision === "approve" ? await approveWorkRecord(record, records, { wage: record.wage, hoursWorked: record.hoursWorked, location: record.location, date: record.date, description: record.description }) : updateWorkRecordStatus(record, decision === "reject" ? "Rejected" : "Requested changes", reason.trim());
    const next = records.map((item) => item.id === record.id ? updated : item); persistRecords(next); setRecords(next);
    if (updated.status === "Verified") await refreshVerifiedPortfolio(next);
    setWorking(false);
  };
  if (!record) return <main className="flex min-h-screen items-center justify-center bg-[#f5f8fc] p-5"><Card className="max-w-md p-7 text-center"><FileText className="mx-auto h-8 w-8 text-slate-300"/><h1 className="mt-3 text-lg font-bold text-slate-900">Verification request not found</h1><Link href="/contractor" className="mt-5 inline-flex text-sm font-semibold text-blue-600">Return to contractor portal</Link></Card></main>;
  const history = record.verificationMetadata?.history || [];
  return <main className="min-h-screen bg-[#f5f8fc]"><header className="border-b border-slate-100 bg-white"><div className="mx-auto flex max-w-6xl items-center gap-3 px-5 py-4 sm:px-8"><Link href="/contractor" className="rounded-xl p-2 text-slate-600 hover:bg-slate-100"><ArrowLeft className="h-5 w-5"/></Link><div><p className="text-xs font-semibold text-blue-600">CONTRACTOR VERIFICATION</p><p className="font-[family-name:'Plus_Jakarta_Sans'] text-lg font-bold text-slate-900">Review work request</p></div></div></header><section className="mx-auto max-w-6xl px-5 py-8 sm:px-8"><div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div className="space-y-6"><Card className="overflow-hidden"><div className="bg-gradient-to-r from-[#102f6b] to-[#087d88] p-6 text-white"><div className="flex items-start justify-between"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-white/15 text-lg font-extrabold">{record.workerName.split(" ").map((name) => name[0]).join("").slice(0, 2)}</div><StatusBadge status={record.status}/></div><h1 className="mt-5 font-[family-name:'Plus_Jakarta_Sans'] text-2xl font-extrabold">{record.workerName}</h1><p className="mt-1 text-sm text-blue-100">Worker ID · {record.workerId}</p></div><div className="grid gap-4 p-6 sm:grid-cols-2"><Detail icon={FileText} label="Job type" value={record.jobType}/><Detail icon={CalendarDays} label="Date" value={new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "long", year: "numeric" }).format(new Date(`${record.date}T00:00:00`))}/><Detail icon={Clock3} label="Hours worked" value={`${record.hoursWorked || 0} hours`}/><Detail icon={MapPin} label="Location" value={record.location}/><Detail icon={BadgeCheck} label="Contractor" value={record.contractorName}/><Detail icon={FileText} label="Supporting documents" value="No document attached"/></div><div className="border-t border-slate-100 p-6"><p className="text-sm font-bold text-slate-800">Job description</p><p className="mt-2 text-sm leading-6 text-slate-600">{record.description || "No job description was provided."}</p></div></Card><Card className="p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Verification history</p><h2 className="mt-1 font-[family-name:'Plus_Jakarta_Sans'] text-lg font-bold text-slate-900">Decision trail</h2></div><ShieldCheck className="h-5 w-5 text-emerald-600"/></div><div className="mt-5 space-y-4">{history.length ? history.map((entry, index) => <div key={`${entry.timestamp}-${index}`} className="flex gap-3"><span className="mt-1 h-2.5 w-2.5 rounded-full bg-blue-500"/><div><p className="text-sm font-semibold text-slate-800">{entry.action}</p><p className="mt-0.5 text-xs text-slate-500">{entry.contractorName} · {new Date(entry.timestamp).toLocaleString("en-IN")}</p>{entry.reason && <p className="mt-1 text-xs text-slate-600">{entry.reason}</p>}</div></div>) : <p className="text-sm text-slate-500">No decision recorded yet.</p>}</div></Card></div>
        <Card className="h-fit p-6"><p className="eyebrow">Contractor decision</p><h2 className="mt-1 font-[family-name:'Plus_Jakarta_Sans'] text-xl font-bold text-slate-950">Confirm this work</h2><p className="mt-2 text-sm leading-6 text-slate-600">Approval adds the record to the trusted passport, then runs the AI consistency and fraud check.</p>{record.status === "Pending Verification" ? <div className="mt-6 space-y-3"><Button onClick={() => update("approve")} disabled={working} className="w-full bg-emerald-600 shadow-emerald-100 hover:bg-emerald-700"><CheckCircle2 className="h-4 w-4"/>{working ? "Confirming and analyzing…" : "Approve work record"}</Button><label><span className="mb-1.5 block text-sm font-semibold text-slate-700">Reason for a rejection or revision</span><textarea value={reason} onChange={(event) => setReason(event.target.value)} rows={3} placeholder="Tell the worker what needs attention..." className="w-full resize-none rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm outline-none focus:border-blue-400 focus:bg-white"/></label><Button variant="outline" onClick={() => update("changes")} disabled={working || !reason.trim()} className="w-full"><MessageSquareWarning className="h-4 w-4"/>Request changes</Button><Button variant="outline" onClick={() => update("reject")} disabled={working || !reason.trim()} className="w-full border-rose-100 text-rose-700 hover:bg-rose-50"><XCircle className="h-4 w-4"/>Reject record</Button></div> : <div className="mt-6 rounded-2xl bg-slate-50 p-4"><StatusBadge status={record.status}/><p className="mt-3 text-sm font-semibold text-slate-800">This request has been decided</p>{record.verificationMetadata?.verificationId && <p className="mt-1 text-xs text-slate-500">Verification ID: {record.verificationMetadata.verificationId}</p>}{record.verificationStatus === "Needs review" && <p className="mt-3 flex gap-2 text-xs leading-5 text-amber-700"><AlertTriangle className="h-4 w-4 shrink-0"/>Needs manual review after the AI fraud check.</p>}</div>}</Card></div></section></main>;
}
function Detail({ icon: Icon, label, value }: { icon: typeof FileText; label: string; value: string }) { return <div className="flex gap-3"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><Icon className="h-4 w-4"/></span><div><p className="text-xs font-semibold text-slate-400">{label}</p><p className="mt-0.5 text-sm font-semibold text-slate-700">{value}</p></div></div>; }
